name: Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Test Angular app
        run: npm run test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production (replace with your deployment steps)
        run: |
          # Add your deployment script or commands here
          # Example: Deploy to Firebase Hosting
          # npm install -g firebase-tools
          # firebase login:ci --no-localhost --open
          # firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
